---
language: go

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      # hammer
      - rpm
      - g++-4.8

cache:
  apt: true
  directories:
    - tools

before-install:
  - export CXX="g++-4.8" CC="gcc-4.8"

install:
  - source scripts/travis-cache.sh

script:
  - mkdir -p /tmp/out
  - ./scripts/ci_build.py

after_failure:
  - tail logs/*

deploy:
  provider: script
  script: /bin/bash scripts/bintray.sh /tmp/out
  on:
    branch: master
